### ISSUE TITLE
Generating and hosting the documentation

### ISSUE THREAD

**Issue by phajy** [astro-group-bristol/DiscJetConnections.jl#3]
I'm experimenting with using Documenter.jl for the code documentation. Gloria is also looking at using Weave.jl for documented code runs.

For Documenter.jl I'm not sure if it is possible to set up an automated process for creating the documentation and hosting it on GitHub, e.g., using a GitHub Action. But I've not done this before so any advice would be appreciated.

**Comment by fjebaker** [comment]
Yes, it is possible to have Documenter automatically build documentation for you -- with Julia this can sometimes be a little inefficient, since the action has to pre-compile the entire environment + dependencies to generate the documentation, but making that more efficient is something I've been meaning to research. I'll keep you posted on what I find.

For now, from an old project of mine, you could use this GitHub action:
```yml
name: docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: julia --project=. -e 'using Pkg; Pkg.activate("."); Pkg.instantiate()'
      - run: julia --project=. docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

With the contents of `make.jl` configuring exactly what is built
```julia
push!(LOAD_PATH,"src")

using Documenter, DiscJetConnections

makedocs(
    # the modules you want to bring into scope go here
    modules=[DiscJetConnections],
    clean=false,
    sitename="Documentation",

    pages = [
        "Home" => "index.md",
        "Internal Methods" => "internals.md"
    ]
)

deploydocs(
    repo="YOUR_REPO_URL"
)
```
